// generated by tscfg 0.9.5 on Tue Jan 15 09:10:16 PST 2019
// source: src/main/resources/orront.spec.conf

package org.mmisw.orr.ont

case class Cfg(
  admin           : Cfg.Admin,
  agraph          : Cfg.Agraph,
  auth            : Cfg.Auth,
  branding        : Cfg.Branding,
  deployment      : Cfg.Deployment,
  email           : Cfg.Email,
  files           : Cfg.Files,
  googleAnalytics : scala.Option[Cfg.GoogleAnalytics],
  mongo           : Cfg.Mongo,
  recaptcha       : scala.Option[Cfg.Recaptcha]
)
object Cfg {
  case class Admin(
    email    : java.lang.String,
    extra    : scala.Option[java.lang.String],
    password : java.lang.String
  )
  object Admin {
    def apply(c: com.typesafe.config.Config): Cfg.Admin = {
      Cfg.Admin(
        email    = c.getString("email"),
        extra    = if(c.hasPathOrNull("extra")) Some(c.getString("extra")) else None,
        password = c.getString("password")
      )
    }
  }
        
  case class Agraph(
    host           : java.lang.String,
    initDelay      : scala.Option[scala.Long],
    password       : java.lang.String,
    port           : scala.Int,
    repoName       : java.lang.String,
    sparqlEndpoint : java.lang.String,
    userName       : java.lang.String
  )
  object Agraph {
    def apply(c: com.typesafe.config.Config): Cfg.Agraph = {
      Cfg.Agraph(
        host           = if(c.hasPathOrNull("host")) c.getString("host") else "localhost",
        initDelay      = if(c.hasPathOrNull("initDelay")) Some(c.getDuration("initDelay", java.util.concurrent.TimeUnit.SECONDS)) else None,
        password       = c.getString("password"),
        port           = if(c.hasPathOrNull("port")) c.getInt("port") else 10035,
        repoName       = if(c.hasPathOrNull("repoName")) c.getString("repoName") else "mmiorr",
        sparqlEndpoint = c.getString("sparqlEndpoint"),
        userName       = c.getString("userName")
      )
    }
  }
        
  case class Auth(
    secret : java.lang.String
  )
  object Auth {
    def apply(c: com.typesafe.config.Config): Cfg.Auth = {
      Cfg.Auth(
        secret = c.getString("secret")
      )
    }
  }
        
  case class Branding(
    contactUs    : scala.Option[java.lang.String],
    footer       : scala.Option[java.lang.String],
    instanceName : java.lang.String,
    logo         : scala.Option[java.lang.String],
    tou          : scala.Option[java.lang.String]
  )
  object Branding {
    def apply(c: com.typesafe.config.Config): Cfg.Branding = {
      Cfg.Branding(
        contactUs    = if(c.hasPathOrNull("contactUs")) Some(c.getString("contactUs")) else None,
        footer       = if(c.hasPathOrNull("footer")) Some(c.getString("footer")) else None,
        instanceName = c.getString("instanceName"),
        logo         = if(c.hasPathOrNull("logo")) Some(c.getString("logo")) else None,
        tou          = if(c.hasPathOrNull("tou")) Some(c.getString("tou")) else None
      )
    }
  }
        
  case class Deployment(
    sparqlEndpoint : java.lang.String,
    url            : java.lang.String
  )
  object Deployment {
    def apply(c: com.typesafe.config.Config): Cfg.Deployment = {
      Cfg.Deployment(
        sparqlEndpoint = c.getString("sparqlEndpoint"),
        url            = c.getString("url")
      )
    }
  }
        
  case class Email(
    account : Cfg.Email.Account,
    from    : java.lang.String,
    mailer  : java.lang.String,
    replyTo : java.lang.String,
    server  : Cfg.Email.Server
  )
  object Email {
    case class Account(
      password : java.lang.String,
      username : java.lang.String
    )
    object Account {
      def apply(c: com.typesafe.config.Config): Cfg.Email.Account = {
        Cfg.Email.Account(
          password = c.getString("password"),
          username = c.getString("username")
        )
      }
    }
          
    case class Server(
      debug : scala.Boolean,
      host  : java.lang.String,
      port  : scala.Int,
      prot  : java.lang.String
    )
    object Server {
      def apply(c: com.typesafe.config.Config): Cfg.Email.Server = {
        Cfg.Email.Server(
          debug = c.hasPathOrNull("debug") && c.getBoolean("debug"),
          host  = c.getString("host"),
          port  = c.getInt("port"),
          prot  = if(c.hasPathOrNull("prot")) c.getString("prot") else "smtps"
        )
      }
    }
          
    def apply(c: com.typesafe.config.Config): Cfg.Email = {
      Cfg.Email(
        account = Cfg.Email.Account(if(c.hasPathOrNull("account")) c.getConfig("account") else com.typesafe.config.ConfigFactory.parseString("account{}")),
        from    = c.getString("from"),
        mailer  = c.getString("mailer"),
        replyTo = c.getString("replyTo"),
        server  = Cfg.Email.Server(if(c.hasPathOrNull("server")) c.getConfig("server") else com.typesafe.config.ConfigFactory.parseString("server{}"))
      )
    }
  }
        
  case class Files(
    baseDirectory     : java.lang.String,
    maxUploadFileSize : scala.Long
  )
  object Files {
    def apply(c: com.typesafe.config.Config): Cfg.Files = {
      Cfg.Files(
        baseDirectory     = c.getString("baseDirectory"),
        maxUploadFileSize = if(c.hasPathOrNull("maxUploadFileSize")) c.getBytes("maxUploadFileSize") else 157286400
      )
    }
  }
        
  case class GoogleAnalytics(
    propertyId : java.lang.String
  )
  object GoogleAnalytics {
    def apply(c: com.typesafe.config.Config): Cfg.GoogleAnalytics = {
      Cfg.GoogleAnalytics(
        propertyId = c.getString("propertyId")
      )
    }
  }
        
  case class Mongo(
    db            : java.lang.String,
    host          : java.lang.String,
    ontologies    : java.lang.String,
    organizations : java.lang.String,
    port          : scala.Int,
    pw            : scala.Option[java.lang.String],
    user          : scala.Option[java.lang.String],
    users         : java.lang.String
  )
  object Mongo {
    def apply(c: com.typesafe.config.Config): Cfg.Mongo = {
      Cfg.Mongo(
        db            = if(c.hasPathOrNull("db")) c.getString("db") else "orr-ont",
        host          = if(c.hasPathOrNull("host")) c.getString("host") else "localhost",
        ontologies    = if(c.hasPathOrNull("ontologies")) c.getString("ontologies") else "ontologies",
        organizations = if(c.hasPathOrNull("organizations")) c.getString("organizations") else "organizations",
        port          = if(c.hasPathOrNull("port")) c.getInt("port") else 27017,
        pw            = if(c.hasPathOrNull("pw")) Some(c.getString("pw")) else None,
        user          = if(c.hasPathOrNull("user")) Some(c.getString("user")) else None,
        users         = if(c.hasPathOrNull("users")) c.getString("users") else "users"
      )
    }
  }
        
  case class Recaptcha(
    privateKey : java.lang.String,
    siteKey    : java.lang.String
  )
  object Recaptcha {
    def apply(c: com.typesafe.config.Config): Cfg.Recaptcha = {
      Cfg.Recaptcha(
        privateKey = c.getString("privateKey"),
        siteKey    = c.getString("siteKey")
      )
    }
  }
        
  def apply(c: com.typesafe.config.Config): Cfg = {
    Cfg(
      admin           = Cfg.Admin(if(c.hasPathOrNull("admin")) c.getConfig("admin") else com.typesafe.config.ConfigFactory.parseString("admin{}")),
      agraph          = Cfg.Agraph(if(c.hasPathOrNull("agraph")) c.getConfig("agraph") else com.typesafe.config.ConfigFactory.parseString("agraph{}")),
      auth            = Cfg.Auth(if(c.hasPathOrNull("auth")) c.getConfig("auth") else com.typesafe.config.ConfigFactory.parseString("auth{}")),
      branding        = Cfg.Branding(if(c.hasPathOrNull("branding")) c.getConfig("branding") else com.typesafe.config.ConfigFactory.parseString("branding{}")),
      deployment      = Cfg.Deployment(if(c.hasPathOrNull("deployment")) c.getConfig("deployment") else com.typesafe.config.ConfigFactory.parseString("deployment{}")),
      email           = Cfg.Email(if(c.hasPathOrNull("email")) c.getConfig("email") else com.typesafe.config.ConfigFactory.parseString("email{}")),
      files           = Cfg.Files(if(c.hasPathOrNull("files")) c.getConfig("files") else com.typesafe.config.ConfigFactory.parseString("files{}")),
      googleAnalytics = if(c.hasPathOrNull("googleAnalytics")) scala.Some(Cfg.GoogleAnalytics(c.getConfig("googleAnalytics"))) else None,
      mongo           = Cfg.Mongo(if(c.hasPathOrNull("mongo")) c.getConfig("mongo") else com.typesafe.config.ConfigFactory.parseString("mongo{}")),
      recaptcha       = if(c.hasPathOrNull("recaptcha")) scala.Some(Cfg.Recaptcha(c.getConfig("recaptcha"))) else None
    )
  }
}
      
